### ISSUE TITLE
Establish standardized guide formatting

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/Website#132]
### Overview
We need to establish consistent formatting across the guides.

### Action Items
  - [x] Audit and fix current guides for consistency
  - [x] Decide on heading hierarchy
  - [x] Audit all guides to get current status (see below)
  - [x] add categories to metadata - #375
     - [x] check/confirm all guide categories - #397
  - [x] confirm builder/contributor usage - #395
  - [x] finalize CSS - #334 - this is down to minor bugs and formatting subtleties  
  -  Deal with title wrap (vertical center? character limit?) - small enough issue, we can set aside and prioritize later
  - [x] Fix obvious content/markup bugs (see below)
  - [x] Address assorted quirkiness (see below)

### Resources/Instructions
- https://github.com/100Automations/Website/issues/43
- https://github.com/100Automations/Website/issues/42
- [Directory for all guides](https://github.com/100Automations/Website/tree/master/_guides)
 - #174 

---

# Guide Review

## Proposed changes to all guides:
- [x] take out the H1 title from the content - it repeats the H1 title in the header - #386

### [Start Contributing](https://100automations.github.io/Website/guides/start_contributing.html)
- [x]  **_UNWRITTEN_** - it's a stub, no info about adding an existing code package #355

### [Using An Automation](https://100automations.github.io/Website/guides/using_an_automation.html)
- [x]  **_UNWRITTEN_** - blank. Propose we delete this guide for now and backlog an issue to create a guide. #388

### [Start Building](https://100automations.github.io/Website/guides/start_building.html)
-  ~_broken link_ : [Guide on Creating an Automation Repo](https://100automations.github.io/Website/guides/url) : page does not exist~ content replaced
-  ~_broken link_ : [automation workflow overview](https://github.com/100Automations/futureautomations/wiki/Workflow-Guide-for-Ideators) : links to create a blank wiki page #354~ content replaced

### [Preparing Your Automation for Publication](https://100automations.github.io/Website/guides/prep-automation-for-publication.html)
narrow. Longer headings are odd in the sidebar
- [x] _formatting: broken headings, goofy sidebar, hr misinterpreted by jekel _ - #385
- [x] broken links: Writing About Your Automation, Supporting Your Automation with Community - #389

### [Creating a Good Read.me for Your Automation](https://100automations.github.io/Website/guides/creating-good-readmes-for-automations.html)
pushed wide by fixed width code
-  _clarify code text with additional styling (quote/indent?)_ - #387 - post-MVP

### [Writing an Article for Your Automation](https://100automations.github.io/Website/guides/writing-articles-for-automations.html)
narrow
- [x]  _has extra hand-made ToC links in the content_

### [Project Card Anatomy](https://100automations.github.io/Website/guides/project_card_anatomy.html)
pushed wide by image

### [Self-Evaluating a New Automation Idea](https://100automations.github.io/Website/guides/self-evaluating-new-automation-idea.html)
longer headings odd in the sidebar

### [Workflow Guide For Builders](https://100automations.github.io/Website/guides/workflow-guide-for-builders.html)
pushed wide by image. text in image accessibility

### [Workflow Guide For Ideators](https://100automations.github.io/Website/guides/workflow-guide-for-ideators.html)
pushed wide by image. text in image accessibility
 

### [Supporting Your Automation with Community](https://100automations.github.io/Website/guides/community-support-for-automations.html)
narrow 

### [Submit Idea](https://100automations.github.io/Website/guides/submit_idea.html)
narrow

### [Write a Short Narrative Description about Your Automation](https://100automations.github.io/Website/guides/writing-short-descriptions-for-automations.html)
narrow

### [Creating a Good Project Image](https://100automations.github.io/Website/guides/creating-good-project-images.html)
narrow 
- [x] _has edit footer_ - pr #377 

### [Creator Overview](https://100automations.github.io/Website/guides/creator_overview.html)
- [x] _empty ToC_ - #378

### [How to suggest a guide for 100 Automations](https://100automations.github.io/Website/guides/suggest-guide-for-100Automations.html)
- [x] _broken markup for link_ #379

### [Write your Open Source Automation Creator Bio](https://100automations.github.io/Website/guides/write-your-opensource-automation-creator-bio.html)
narrow
- [x] **messed up ToC due to misused headings** - #380

**Comment by nahyungkim1220** [comment]
# Title
Description of guide

Navigation
- [Topic 1](#topic1)
- [Topic 2](#topic2)
- [Topic 3](#topic3)

<a name="topic1"></a>
### Topic 1
Description of topic

#### Example 1:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae diam sed ex feugiat auctor et a nisl. Maecenas semper maximus lectus at molestie. Donec convallis feugiat neque ac faucibus. Nunc ornare malesuada elementum. Morbi vulputate erat vitae mollis pellentesque. Nunc volutpat mauris a velit gravida venenatis. 
>
> Integer ligula sem, cursus dignissim dolor nec, mattis commodo felis. Curabitur vel tortor non enim ullamcorper pellentesque nec sit amet elit.

**Includes:**
- Lorem ipsum
- Lorem ipsum

**Does not include:**
- Lorem ipsum
-Lorem ipsum

#### Example 2:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae diam sed ex feugiat auctor et a nisl. Maecenas semper maximus lectus at molestie. Donec convallis feugiat neque ac faucibus. Nunc ornare malesuada elementum. Morbi vulputate erat vitae mollis pellentesque. Nunc volutpat mauris a velit gravida venenatis. 
>
> Integer ligula sem, cursus dignissim dolor nec, mattis commodo felis. Curabitur vel tortor non enim ullamcorper pellentesque nec sit amet elit.

**Includes:**
- Lorem ipsum
- Lorem ipsum

**Does not include:**
- Lorem ipsum
- Lorem ipsum

**Comment by superbunker** [comment]
Didn't get to wiki page yet -- should have that set up later today. 
But a little concerned that this overall thing might be too wooly for MVP?

**Comment by superbunker** [comment]
Refocused on just auditing the markup and basic structure. There's not a ton of changes, so I'll just review them here.

Guides using "standard" markup: 
 - _creating-good-readmes-for-automations.md_
 - _prep-automation-for-publication.md_
 - _self-evaluating-new-automation-idea.md_
 - _writing-articles-for-automations.md_


Three guides have some non-standard markup:

_writing-short-descriptions-for-automations.md_ — doesn't use H2s
**proposed changes:** just bump the h3s & h4s up a level

 _suggest-guide-for-100Automations.md_ — all H3, some bold-as-heading
**proposed changes:** Could use a little editing to clarify the sections, then apply headings by level

 _community-support-for-automations.md_ — doesn't use H2s
**proposed changes:** bump H3s to H2s. Simplify structure so H3 isn't necessary by removing word "overview" and add descriptive term at beginning of three bullet items. For example:  
> ## File_Name.md
> This file does very helpful things
>  - Template: file_link 
>  - Example: file_link
>  - Resources: links

overall:  "END" is an H4 
make this an h2 or a non-heading tag?

**Comment by superbunker** [comment]
Process question: would it be better to edit the guides in my fork of Website and PR that, or individually edit/PR each edited guide?

**Comment by Olivia-Chiong** [comment]
Please create individual PRs for each and tag @Olivia-Chiong or @NivenPrasad for review.

**Comment by superbunker** [comment]
Made markup changes to _writing-short-descriptions-for-automations_. Mostly just changed headings to properly nest.  PR #153

Made markup and some content structure changes to _suggest-guide-for-100Automations_  PR #154

**Comment by superbunker** [comment]
revised _community-support-for-automations.md_ 
Some notable formatting changes, gentle content edits, and a proposed End of File denotation
PR #157

**Comment by superbunker** [comment]
revised _community-support-for-automations.md_ 
Some notable formatting changes, gentle content edits, and a proposed End of File denotation
PR #157

**Comment by NivenPrasad** [comment]
Nice work @superbunker. Now approved #153 and #154. Inclined to have @ExperimentsInHonesty or @Olivia-Chiong review #157 given extent of changes/HTML edits in there.

**Comment by superbunker** [comment]
Drafted a guide to guide formatting in the wiki: 
https://github.com/100Automations/Website/wiki/Guide-Template

**Comment by Olivia-Chiong** [comment]
Refer to this markdown https://github.com/hackforla/website/wiki/Template-of-a-project.md-file

**Comment by superbunker** [comment]
created [guide_template.md](https://github.com/100Automations/Website/wiki/guide_template.md) and cleaned up the [ Guide to the Guide Template](https://github.com/100Automations/Website/wiki/Guide-to-the-Guide-Template)

**Comment by henlatourrette** [comment]
Assign back to @superbunker when dependency met.

**Comment by superbunker** [comment]
Propose that we get rid of the footer in all the guides ("END" or "END OF FILE" and the invitation to edit)

**Comment by superbunker** [comment]
@superbunker will try to figure out what's going on these days

**Comment by superbunker** [comment]
i'm working on it, more or less

**Comment by superbunker** [comment]
Bonnie: "Some of the guides look different than other guide pages.  That should not be possible if we are using collections properly.  Please make an issue to review with a bug label to figure out why and fix."

**Comment by superbunker** [comment]
moved Guide Review to main issue for easier tracking

**Comment by superbunker** [comment]
Proposed change to all guides: take out the H1 title from the content, since it repeats the H1 title in the header

**Comment by superbunker** [comment]
Carlos gunna take a swing at the weird CSS, in particular the goofy right margin of the content and smooshing the sidebar off screen when theres fixed width content

**Comment by superbunker** [comment]
Carlos, still swingin'

**Comment by superbunker** [comment]
The weird with issue seems to have been dealt with, at least on desktop.

**Comment by superbunker** [comment]
Guide formatting finalized. Major bugs and quirks fixed.
