### ISSUE TITLE
Design System | Create "Needs Help" CardTab component

### ISSUE THREAD

**Issue by CamilaArias** [100Automations/Website#172]
## Overview
Create a Figma component for the `Help Needed` tab that is added on `Automation Cards` that have specified the help they need. Evaluate ticket at the end to potentially use this format for future component creation or as a guide for creating components on our Design System.
Recommended to watch resources first if needed to learn about auto-layout, components and variants.

### 🚀 Stage 0 - Set Up

- [x] Duplicate [this frame](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=1975%3A60) and the Comments list next to it (it has auto-layout so you can create new items by duplicating the existing one).
- [x] Set frame name to `CardTab` and update Section Title and Used In accordingly.
- [x] Set stroke of frame to the `In Progress` style (orange).

### 💠 Stage 1 - Component creation

- [x] Create Help Needed - `Collapsed`
  - [x] Use existing colours and typography styles.
    - [x] If you need to create a new typography style because the current ones don't work, create it with a size multiple of 4, or just even number if needed.
    - [x] Store the style in `Typography/Detail`.
    - [x] Add it with its values at the end of [Typescale slide](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=1432%3A2167)
  - [x] Use border-radius value as defined in the `Borders` slide
  - [x] Make it auto-layout. Set a fixed width and use spacing (padding in this case) values that are multiple of 4 (assume multiple of 4 or even number for small amounts every time we talk spacing). Refer to resources below for help.
  - [x] Create component. Name it `CardTab/Collapsed`.

- [ ] Create Help Needed - `Expanded`
  - [x] Duplicate the component you just created. Detach the instance (no longer a component). Call it `CardTab/Expanded`.
  - [x] Create an `Unordered List` with auto-layout. Create typography style as needed following steps explained above. Have a list with 3 items this way, set spacing between them. Set the width to be "Fill Container". Create a component out of this list, `UnorderedList`.
  - [x] Drag the list component under the "Help Needed" text of `CardTab/Expanded`. Make the tab heading and the list be aligned vertically if it's not already.
  - [x] Adjust spacing between heading and list as needed, also between list content and edge of the tab.
  - [x] Verify a second line is created accordingly for a long list item (limited by the "Fill Container" constraint set previously and the padding of the tab).
  - [x] Create a component out of this (it will keep the `CardTab/Expanded` name). The list component will be automatically moved out of the tab and the CardTab component will be using an instance of it. This is expected.

- [x] Select both components and click `Combine as Variants`.
- [x] Name the property `Status`, and the value of it should be `Collapsed` and `Expanded` for the corresponding component.

### 📄 Stage 2 - Documentation

- [x] DISCUSSION: How long should we allow the tab to be? This will also depend on what we tell people they should set as their "Help Needed" items.
- [x] Add a `Documentation` section on the slide and explain how the component works. For example, when is this component shown, how to toggle between both states, how many lines can be put on the list before the tab gets longer than the card's cover picture.

### 👩‍🏫 Stage 3 - Team Analysis

- [ ] Provide feedback on issue structure and clarity of steps. Review with team and discuss modifications and improvements to be made to set this issue as a helping guide for creation of future components.

#### Design System page
[Figma file](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=243%3A363) 

#### Videos
[About auto-layout](https://www.youtube.com/watch?v=TyaGpGDFczw)
[About components](https://www.youtube.com/watch?v=k74IrUNaJVk)
[About variants](https://www.youtube.com/watch?v=y29Xwt9dET0)
[Components and variants](https://www.youtube.com/watch?v=gUQjMoW1N_s)

#### Figma Playgrounds - Learn with interactive files
[Auto-layout](https://www.figma.com/community/file/784448220678228461/Figma-Auto-Layout-playground)
[Variants](https://www.figma.com/community/file/903303571898472063/Figma-Variants-Playground)

**Comment by susantangux** [comment]
@CamilaArias @mcspach Hi Camila - I've updated the "Needs Help" card tab component set and added some documentation. Please review. Upon your approval, Matthew will be able to implement. Thx!

**Comment by susantangux** [comment]
@CamilaArias @mcspach 
Here's updated homepage with new project cards (square corner in upper right) and card tabs
![Homepage Mockup](https://user-images.githubusercontent.com/78511203/110268088-f39d3700-7f75-11eb-8d44-4dbf2314d484.png)

**Comment by CamilaArias** [comment]
LGTM @susantangux 
Let's just add that the toggle between states happens when you click on the tab, and the colour styles used, like in the `labels` slide.

**Comment by susantangux** [comment]
> LGTM @susantangux
> Let's just add that the toggle between states happens when you click on the tab, and the colour styles used, like in the `labels` slide.

@CamilaArias Done! BTW- how would people know that "Needs Help" tab is clickable? Do we need to think about that? LMK when you think it's ready to hand off to Matthew. Thx!

**Comment by henlatourrette** [comment]
This is completed.
