### ISSUE TITLE
Site Launch Checklist

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#300]
### Overview
We need to plan how to do the Launch.

### Action Items

**Phase 0** -  finish plan
- [x] Finish Plan

**Phase 1** - get ready
- [x] Finish the About Page #258 
- [x] Finish the Press Page #351 
    - [x] Finish the Team Page #255 
    - ~create a PDF for the press release~ - leaving it as a google doc for now
- [x] Finish the "All Guides" page #322 
- [x] Finish all the MVP Guides #132 : [Guide Review](https://github.com/100Automations/Website/issues/132#issuecomment-877730377)
    - [x] make sure "builder" and "contributor" are used correctly #395 
- [x] Establish the Future Automations process : point to guides, hope for best

**Phase 2** - Fix All The Things
- [x] Fix everything that’s _obviously_ broken 
   - [x]  Check issue from the CoP feedback #276 
   - [x]  Check issue from the Hackathon feedback #296 
- [x] Pass UAT (User Acceptance Test) - #410 
   - [x]  Check the website requirements #25 
   - [x]  Check the UAT document #410 

**Phase 3** - _soft launch!_
- [x] Soft launch - Real Site live (put a “Beta” image on the logo ?)
   - [x] get site to load #416
- [ ] QA testing (analytics, accessibility, etc) #343
     - [x]  Create sectional meta-issues for bug tracking (Home/About, Press, Guides)
     - [x]  Check for issues with the "Bug" label
     - [x] Usability test : #431
        -  [Ava test results](https://docs.google.com/spreadsheets/d/1WrcH6vdlq9cZTddb7hySPXd94sXCbbgY/edit#gid=1545691657)
- [ ] Test FA process with a beta case, document it #352
- [ ] Bug fixing, finish pending stuff 

**Phase 4** - connect and promote
- [ ] Finish Pitch Deck and practice #345 
- [ ] Talk about it at HfLA Team meetings (define meetings - need an issue for this)
- [ ] Attend events and Talk about it

**Phase 5** - _Official Launch!_
- [ ] Set official launch date 
- [ ] Invite people to the official launch party
- [ ] Launch Party

### Resources/Instructions
[Google Docs Launch Plan](https://docs.google.com/document/d/1qCO9FZHMnM7Gj0DcpImKs2gJ0faKY8RSN_c_vEMnWds/edit)

**Comment by henlatourrette** [comment]
We are thinking on adding new issues to create logos for the brand new automations we have as proposals.

**Comment by superbunker** [comment]
Will prepare a visual timeline of launch schedule at next product meeting

**Comment by henlatourrette** [comment]
I just read about this site about press releases that could be useful for promoting our website: https://www.helpareporter.com/

**Comment by henlatourrette** [comment]
We believe it's a good idea to focus mainly on the HfLA community. So, in order to add new automation we could just go and talk to the other projects and ask one by one about automation they might be requiring or already using that we can have on our repository.

**Comment by henlatourrette** [comment]
Launch Timeline (Draft 1)

**Phase 0** -  finish plan
- [x] Finish Plan


**Phase 1** - get ready
- [ ] Finish the About Page #258 
- [ ] Finish the Press Page #351 
    - [ ] Finish the Bio Page #255 
- [ ] Finish the "All Guides" page #322 


**Phase 2** - Fix All The Things
- [ ] Fix everything that’s _obviously_ broken https://github.com/100Automations/Website/issues/25
   - [ ]  Check the website requirements #25 
   - [x]  Check issue from the CoP feedback #276 
   - [x]  Check issue from the Hackathon feedback #296 
   - [ ]  Check for issues with the "Bug" label
- [ ] Pass UAT (User Acceptance Test) https://github.com/100Automations/Website/issues/25
- [ ] Finish Pitch Deck and practice #345 

**Phase 3** - _soft launch!_
- [ ] Soft launch - Real Site live (put a “Beta” image on the logo ?)
- [ ] Talk about it at HfLA Team meetings (define meetings - need an issue for this)
- [ ] QA testing (analytics, accessibility, etc) #343

**Phase 4** - connect and promote
- [ ] Attend events and Talk about it
- [ ] Bugs fixing, finish pending stuff 
- [ ] Invite people to the official launch party

**Phase 5** - _Official Launch!_
- [ ] (Remove Beta image on the logo)
- [ ] Launch Party

**Comment by henlatourrette** [comment]
We need to make sure Mobile design is included in the UAT as well.

**Comment by henlatourrette** [comment]
We need to make a list of the pages that need to be finished for launch -> and to define what's a blocker and what's a nice to have.

**Comment by henlatourrette** [comment]
Ideally, we need to take 10mins each meeting to check the plan and see where we are at

**Comment by superbunker** [comment]
Might be best to move the plan into the initial post, so the to-do items are tracked

**Comment by superbunker** [comment]
Added finishing all the MVP guides to the checklist

**Comment by superbunker** [comment]
Checking off Press page, although there is a layout bug with wide screens #401

**Comment by superbunker** [comment]
We're down to small bugs and quirks (eg: team page top border, mobile menu behavior.)
Phase 1 development is done.
