### ISSUE TITLE
QA on Live site 

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#343]
### Overview
We need to do a check-up on the Live Site

### Action Items
- [x] accessibility
   - [x] #420
   - [x] run test(s) - see accessibility test folder in google drive
   - [x] review results - ongoing, see issue #492
- [x] verify analytics functionality 
   - [x] set up (#23)
- [x] Fix the bugs
   - [x] find and indentify
   - [x] prioritize and create issues #433 
   - [x] fix - high impact bugs fixed. low priority bugs have been backlogged 

### Resources/Instructions

**Bug Tracking**
   -  #424
   -  #425
   -  #426
   -  #427
   -  #428

**Bug Tracking Tracking**
 - #433 

**Bug Priority Code:**
- :heart: - not broken/not fixing 
- :eyes: - need to take a look
- :rocket: - broken/high priority
- :+1: - issue logged/created : #433

**Comment by superbunker** [comment]
Initial round of bug hunting and fixing is complete. Lower priority bugs and accessibility improvements are ongoing
