### ISSUE TITLE
Define a Process to handle the Future Automations

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#352]
### Overview
We need to define a clear process that we can follow to develop the automations that get through the future automations funnel.

### Action Items

- [x] Brainstorm Action Items
- [ ] Define Clear process
- [ ] Establish staffing needs
- [ ] Review it with the team

### Resources/Instructions
- guide: [Start Building](https://100automations.github.io/Website/guides/start_building.html)
- guide: [Start Contributing](https://100automations.github.io/Website/guides/start_contributing.html) 
- #469 
- #354
- #12
- #315
- #234
- #355
- "Guide on Creating an Automation Repo" linked from [Start Building](https://100automations.github.io/Website/guides/start_building.html) does not exist #357
- https://github.com/100Automations/Website/issues/127#issuecomment-830691542
- #384

**Comment by henlatourrette** [comment]
I'll try to come up with some process, considering the already available documentation.

**Comment by henlatourrette** [comment]
Some ideas from the meeting:
Slack bot to send a message saying that there's a new submission.
Someone to check the new automation.

**Comment by henlatourrette** [comment]
After reviewing the main guides and everything, I think that the best way to begin working towards this is to:

- either assign a specific time on each team meeting to review the Future Automations Status or
- create different meetings specifically to work towards moving forward with the automation projects.

**Comment by henlatourrette** [comment]
[ draft ]
Automation Workflow Process:

Automations can come from different channels:
 - Google Form
 - GitHub

Once the automation is properly submitted, it would appear on the "Future Automations Board" under the "Ice Box" column.
{should a slackbot notify about this event?}

On each Product team meeting (or whole team meeting) there should be a time assigned to review the whole Future Automations Board and decide on the next steps for each Issue. Each issue is a Project itself that may need different action steps such as:
* Product Management
* Roles Opening
* Engeering tasks
* Marketing 
* etc.

After that, a follow-up has to be made on the Automations.

**Comment by superbunker** [comment]
Re: roles and staffing (#27):

- Who evaluates incoming automations?
   - types of submission:
      - ideas
      - incomplete projects
      - complete packages
   - What are the acceptance criteria for new automations?
- Who makes status changes? 
   - in progress
   - own repo
   - listing on home page
   - change in help needed
- Who handles access to individual repos?
- Who works on ideas and incomplete automations?
   - how is that assigned
   - how are issues tracked
   - who tracks/manages progress
- Who works on patching existing automations?
- Who reviews existing automation? 
   - For what? (security, updates, etc)
   - How often?
- Who decides current status and help needed?
   - What triggers an update?
- Who are the project owners for each automation?
- Who contacts project owners and keeps process moving?
- Who takes over when the original developer/project owner is no longer available?
- Who keeps track of all the repos and coordinates their issues?
   - will there be an aggregator for the issues?
- How do we (do we?) assign issues outside 100 Automations team? 
   - development
   - code review
   - bugs
   - testing
   - design
   - documentation
   - user support

**Comment by henlatourrette** [comment]
Suggestions made by Bonnie:
A simple process could be:
- Talk directly to the Automation Ideators/Creators and do something like a "Customer Success Management" process

**Comment by superbunker** [comment]
For locating a test case of reusable code Bonnie suggests:

- **Hack for LA site**: _sorting function for JSON objects._ **it's done.** Tyler Thome wrote it
- Food Oasis: **John Darragh** <-- prob has most time

Top Suggestions:
- 311 Data: Adam Kendis (front end)
- Engage: **Eli Selkin**
- Expunge Assist: Gretchen (PM) - reach out for name of tech lead
- VRMS: **Alex Anakin** (tech lead), **Jason Wong**

also:
- **Civic Tech Index:** Kevin Ashworth
- **Ballot Nav**: Randal PM, Jacob Mensch (tech lead), anullvalue (super smart, back pocket full o' auto)
- **Lucky Parking**: Greg Pawin (data)
- **TDM Calculator**: Claire Nguyn
- **Home Unite Us**: Tyler Thome

**Comment by superbunker** [comment]
Niven contacted Ava, will partner up in the near future

**Comment by henlatourrette** [comment]
I was reviewing the documentation looking for a Step by Step process that we can send Ava to. And I found that we don't have the page for "Workflow Guide for Ideators" but we do have an issue with the information already there -> #222 

Therefore, I think that what we need to do first is: Create the Page for "Workflow Guide for Ideators" and then send her to the "Submit Idea" guide, where she would be able to follow the guide and submit her automation. 

![image](https://user-images.githubusercontent.com/21250505/126238362-f090219c-e201-4fca-9c5d-478690765224.png)

After that, we may need to check the status for the next steps.

**Comment by henlatourrette** [comment]
Bonnie suggested that the process we use should be:

- Send people to our website.

**Comment by henlatourrette** [comment]
* Send people to our website (ideators/builders/contributors).
* Perform a weekly check to see whether there are new proposals or repositories submitted to the pipeline.
* For each new automation, verify that the processes are being followed according to the guides.
* If necessary, get in touch with the people submitting the automation proposals.

**Comment by superbunker** [comment]
@henlatourrette will contact John Darragh on monday

**Comment by henlatourrette** [comment]
I contacted John and he is not sure whether the Github actions they use can be considered "automation". Need to get back to him with something.

**Comment by superbunker** [comment]
Who has ownership of 100automations (in h4la settings (?) )
- cnk 
- darren pham 
- bonnie
- jared fowler
- joel parker henderson
- kian baddie 
- niven 
- olivia
- raudel blazquez munoz 
- sophia alice 
- tim malsted 

currently all members can create repos at 100a 

people in the org/we trust : ask them to create private repos 
outsiders: we create private repo

**Comment by superbunker** [comment]
- [ ] @superbunker will create an issue (or redo this one) to focus on builders guide and getting Ava's repo created

**Comment by henlatourrette** [comment]
I propose to move this issue to the prioritized backlog while we focus on other stuff right now.

**Comment by superbunker** [comment]
We won't be able to launch an MVP until users are able to take action. 

For now, keeping this in "in progress" (or maybe "review") as an anchor point for other issues on this topic.

**Comment by henlatourrette** [comment]
@superbunker suggests to allow HfLA website team members to have access to our repo sort of automatically so that they can add their projects in here as well.

**Comment by henlatourrette** [comment]
Ava insisted on adding her project now that it's still fresh on her head. So I asked her to add it to the [Future Automations board](https://github.com/100Automations/futureautomations/projects/1). She did add it [in here](https://github.com/100Automations/futureautomations/issues/40) but she wasn't able to place it into the right column

![image](https://user-images.githubusercontent.com/21250505/136475057-890ae3db-08a9-45ce-ad7d-e0cda51bae9a.png)

**Comment by superbunker** [comment]
At the last product meeting, we decided/clarified that we have one workflow that everyone follows, and one intake point - the google form. This will require widespread revision of the guides, and perhaps some other UI text. We should probably create another (epic) issue to research and track all the necessary changes.

**Comment by henlatourrette** [comment]
To clarify the Defined Process:

1. All automation proposals should go through the [Google Form.](https://docs.google.com/forms/d/e/1FAIpQLSeGJrU92Tj5Ft763MMWpSwyB6VqctPXzu8WKIy4xTjf1nJg0Q/viewform). People shouldn't directly add proposals as issues on the project board.
2. The product Team will review the [FutureAutomations KanBan Board](https://github.com/100Automations/futureautomations/projects/1) periodically and look for New Automation Proposals under the "New Ideas Ice Box" column.
3. According to each automation status under the workflow, we will also periodically define the next steps for each of them. The Next Steps can include:
    Getting in touch with the person who submitted the proposal.
    Add him/her to the org so that he/she can begin working on the automation or adding more details.
    Look for the required resources for each automation.
    Etc.

**Comment by henlatourrette** [comment]
As an update, there's issue #469 through which we are also doing a full audit on the User Journeys including the different user personas: 
* Builder
* Ideator
* Contributor

**Comment by henlatourrette** [comment]
We finally have a new Automation published on the site now - which was the result of working closely with the author in order to test the workflow.

The details can be found on its [own issue under the Future Automations project board.](https://github.com/100Automations/futureautomations/issues/47).

**Comment by henlatourrette** [comment]
We're still working on reviewing the workflow we used to publish the latest automation and we are [documenting the steps](https://www.figma.com/file/IL9pYQDnj1V0emSZK3UECa/workflow%3A-builder?node-id=5%3A2) we followed on the issue: 

- #469
