### ISSUE TITLE
Swap the usage of "Build" and "Contribute"

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#395]
### Overview
We currently use "build" to describe adding to an existing project and "contribute" to describe adding already-written code. For clarity, we'll reverse this throughout the site, so "build" refers to creating/adding a new project, and "contribute" refers to working on an existing project.

### Action Items

- [ ] locate all instances of this usage
   - [x] Home page calls to action
   - [x] [creator overview](/Website/guides/creator_overview.html)
   - [x] [start building](/Website/guides/start_building.html)
   - [x] [start contributing](/Website/guides/start_contributing.html)
- [x] identify content that needs to be re-written
- [x] make changes
- [x] review/confirm
- [x] merge

### Resources/Instructions
- #384 
- #127

**Comment by superbunker** [comment]
Change has been made site wide. Will keep eye out for further instances
