### ISSUE TITLE
Bug Tracking: Home Page

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#424]
### Overview

We need to define the problems with the Home page on the site so that we can fix or delay the fixes until after MVP

### Action Items
- [x] In a comment below: Identify a bug 
  - [x] provide a screen shot of problem
  - [x] details on how to replicate
  - [x] provide any appropriate links that would be useful.
- [ ] Product/development will review the bugs, combine related coding into new issues and determine prioritization for them.

### Resources
- [Home Page](https://100automations.org) 
- [Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373)

**Bug Priority Code:**
- :heart: - not broken/not fixing 
- :eyes: - need to take a look
- :rocket: - broken/high priority
- :+1: - issue logged/created : #433

**Comment by superbunker** [comment]
actively working this bug for the automation cards: #411

**Comment by susantangux** [comment]
Homepage desktop and mobile webpage images exported from Figma. Please compare live site to these Figma image files:
<img width="1441" alt="Homepage_Desktop" src="https://user-images.githubusercontent.com/78511203/131231916-076fa7b7-a177-4d5a-b118-27c3af9634cc.png">
<img width="360" alt="Homepage_Mobile" src="https://user-images.githubusercontent.com/78511203/131231920-0db40e10-9786-465b-82e5-72f9bfea927b.png">

**Comment by superbunker** [comment]
@ExperimentsInHonesty from slack:

On this file we need to change out the url the image is coming from to come  from the repo
https://github.com/100Automations/Website/blob/gh-pages/_guides/project_card_anatomy.md
The image is coming from ![project card anatomy image]https://raw.githubusercontent.com/100Automations/Website/gh-pages/assets/images/guides/project_card_anatomy-0320_1319.png but should be located in the repo instead. (edited)

**Comment by nahyungkim1220** [comment]
Probably really minor, but on PC, noticed the colors for the top buttons don't match between Figma and the live page. (Guides is supposed to be a darker color)

**Figma**
<img src ="https://user-images.githubusercontent.com/43450074/131772517-8e9522d7-9cef-46f1-91ff-ec6b0ae9616f.png" width = "500" />


**Live Page**
<img src ="https://user-images.githubusercontent.com/43450074/131772460-f0f009c4-d22f-437a-8014-8fa35b711bae.png" width = "500" />

**Comment by nahyungkim1220** [comment]
On mobile (android/chrome), the gap between 100 Automations and Getting Started sections is longer on the live page than Figma. 

**Figma**
<img src= "https://user-images.githubusercontent.com/43450074/131774125-64ec2fb7-13b9-4de3-93c6-220054a3b07d.png" width = "300" />


**Live Page**
<img src = "https://user-images.githubusercontent.com/43450074/131774021-043fd888-e05c-4385-8aad-05d2267ead3a.png" width = "300" />

Issue created from this comment: #437

**Comment by nahyungkim1220** [comment]
On mobile, the Guides section doesn't match on Figma and the live page.

1) Figma and Live page are compiled in different formatting.
2) Button says "See All Guides" on figma and "Show All Guides" on the live page. Personally, I prefer "See All Guides" - it sounds more user-friendly. 

**Figma**
<img src = "https://user-images.githubusercontent.com/43450074/131775810-b15427a2-1742-4d2e-a7bc-ee49e3153563.png" width="300" />


**Live Page**
<img src = "https://user-images.githubusercontent.com/43450074/131775712-e8ef4751-0fbe-4913-b5da-9bc1cb2efcc9.png" width ="300" />

**Comment by nahyungkim1220** [comment]
At the bottom of the page on mobile, the placement of logo and text alignment for Hack LA is different for Figma and the live page. 

(Personally, I prefer the current format as it is on the live page because it differentiates itself from the main content and has a link to Hack for LA. But that's up to the designers!)

**Figma**
<img src = "https://user-images.githubusercontent.com/43450074/131775389-e4d66f7d-d11a-490c-97ae-8b51eba456d2.png" width ="300" />

/
**Live Page**
<img src= "https://user-images.githubusercontent.com/43450074/131775344-1bb0570e-5208-4387-9471-ae593c089f06.png" width ="300" />

**Comment by superbunker** [comment]
iPhone 6s Safari:

![IMG_0507](https://user-images.githubusercontent.com/47950704/131790763-b1250ae7-54b2-422f-a714-a7495ab35f9c.png)

created issue #438

**Comment by superbunker** [comment]
iPhone 6s Safari:

![IMG_0508](https://user-images.githubusercontent.com/47950704/131790824-367154a0-4347-4d58-956a-6f2203c52d34.png)

Created Issue #438

**Comment by superbunker** [comment]
iPhone 6s Safari:

![IMG_0509](https://user-images.githubusercontent.com/47950704/131790859-fbd9896c-4ee4-49e3-8a69-ae21008c5ebc.png)

Issue #438 created from this comment.

**Comment by ExperimentsInHonesty** [comment]
Here is what the homepage looks like for me:
Iphone 6plus with chrome browser

See formatting of the title and words and button, but also the hamburger menu is way too tiny.
![16515](https://user-images.githubusercontent.com/37763229/131932299-9faf4c83-a3b0-4a85-8806-bc6bc5f1b6db.jpg)

**Comment by citrusapple** [comment]
Bug: Automation cards hack for LA icons do not have hyperlink #455

**Comment by superbunker** [comment]
issues moved to #433
