### ISSUE TITLE
Bug Tracking: About Page

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#425]
### Overview

We need to define the problems with the About page on the site so that we can fix or delay the fixes until after MVP

### Action Items
- [x] In a comment below: Identify a bug 
  - [x] provide a screen shot of problem
  - [x] details on how to replicate
  - [x] provide any appropriate links that would be useful.
- [x] Product/development will review the bugs, combine related coding into new issues and determine prioritization for them.

### Resources
- [About Page](https://100automations.org/about) 
- [Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373)

**Bug Priority Code:**
- :heart: - not broken/not fixing 
- :eyes: - need to take a look
- :rocket: - broken/high priority
- :+1: - issue logged/created : #433

**Comment by susantangux** [comment]
"About Us" desktop and mobile webpage images exported from Figma. Please compare live site to these Figma image files:
<img width="1440" alt="About Us_Desktop" src="https://user-images.githubusercontent.com/78511203/131231955-127c1837-baca-4e16-ad5c-4f7dad1a0e0b.png">
<img width="360" alt="About Us_Mobile" src="https://user-images.githubusercontent.com/78511203/131231957-64d477a9-110f-4830-969c-75f8ecfec95b.png">

**Comment by Clue355** [comment]
//On Desktop:

no space to the left of the paragraph on the top section of the page

![Screenshot from 2021-09-02 15-12-15](https://user-images.githubusercontent.com/54788134/131909951-46fa71bb-ecef-4afd-a703-4380fcfa3b47.png)

created issue #439 for this

middle section goals are spaced apart too far

![Screenshot from 2021-09-02 15-12-02](https://user-images.githubusercontent.com/54788134/131910139-9bce4c1c-2b0b-4200-98f5-8ca75ad1c85f.png)

Issue #442 created for this

Bottom section titles above the paragraphs look too small will have to confirm by looking at the code. 

![Screenshot from 2021-09-02 15-12-40](https://user-images.githubusercontent.com/54788134/131910490-eeeccfeb-c660-4d05-90ea-de939a8134d4.png)

issue #444 created for this

Botton section large title looks off with the spacing

![Screenshot from 2021-09-02 15-20-13](https://user-images.githubusercontent.com/54788134/131910743-30eac077-7933-4798-9876-bcf6a3d886cb.png)

Issue #445 created for this.

//On Mobile:

paragraph is not above numbers

![Screenshot from 2021-09-02 15-23-17](https://user-images.githubusercontent.com/54788134/131911243-e0179caf-31b7-44d0-9248-cf1bc168adbc.png)
Issue #446 created for this

spacing to the left and right of goals look a little small

![Screenshot from 2021-09-02 15-23-52](https://user-images.githubusercontent.com/54788134/131911334-dd28d98c-2531-490f-9ac0-2c6f9b9e642c.png)

Issue #447 created for this.

 Titles are to small or have incorrect alignment. 

![Screenshot from 2021-09-02 15-24-17](https://user-images.githubusercontent.com/54788134/131911383-0d60f901-3c7d-4d03-af94-04b5beae60bd.png)

Issue #448 created for this.

Icons are not aligned next to each other in a row instead of a column

![Screenshot from 2021-09-02 15-24-32](https://user-images.githubusercontent.com/54788134/131911509-a9d15ee0-1689-48d8-b75a-ea471b422150.png)

Issue #449 created for this

**Comment by superbunker** [comment]
These screenshots are responsive desktop, not native mobile

**Comment by superbunker** [comment]
issues collected under #433
