### ISSUE TITLE
Bug Tracking: Press Section

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#426]
### Overview

We need to define the problems with the Press page on the site so that we can fix or delay the fixes until after MVP

### Action Items
- [x] In a comment below: Identify a bug 
  - [x] provide a screen shot of problem
  - [x] details on how to replicate
  - [x] provide any appropriate links that would be useful.
- [x] Product/development will review the bugs, combine related coding into new issues and determine prioritization for them.

### Resources
- [Press Page](https://100automations.org/about) 
- [Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373)

**Bug Priority Code:**
- :heart: - not broken/not fixing 
- :eyes: - need to take a look
- :rocket: - broken/high priority
- :+1: - issue logged/created : #433

**Comment by superbunker** [comment]
@mdothman reports: mobile bug -  _"Contact info is, y'know, kinda squished by the little wave"_

*added to list in #433*
related to https://github.com/100Automations/Website/issues/426#issuecomment-908844584

**Comment by superbunker** [comment]
@ExperimentsInHonesty: margins dont match figma


--- 
@superbunker: I think this involved the mobile margins? if so, it's issue #438.  if it was the press page, issue: #451

**Comment by ExperimentsInHonesty** [comment]
When you click on the link to the logos, it goes to a general design folder https://drive.google.com/drive/folders/1lNXA9jYBauZDz7RgY18-N71jaInZz6ND
It should go to a folder with just the logo assets.

CORRECTED LINK:
https://drive.google.com/drive/folders/1z9nRpZVRotIaTt4e_ng6N7Svtavab0Z6?usp=sharing

**Issue created: #434**

**Comment by ExperimentsInHonesty** [comment]
The icon/cards are resizing inappropriately when you narrow the browser window size. They should remain the same size background card and either stack or whatever behavior is desired (wouldn't it be cool if we had up to date figmas that explained the desired layout for different screen sizes ![image](https://user-images.githubusercontent.com/37763229/131055823-8a452c14-0892-4dc4-a9c4-76e7c1c2df51.png)


**Issue #440**

**Comment by ExperimentsInHonesty** [comment]
The layout and font color of the press release section does not match the figma
Live page
![image](https://user-images.githubusercontent.com/37763229/131056038-9b792f5b-a473-4736-978f-e5715344925b.png)

figma
![image](https://user-images.githubusercontent.com/37763229/131056174-62968fee-273b-405e-8660-aaf8936303be.png)

Its possible that the font colors are not as selected in the figma throughout the site. I did not check that yet.  Without going into a whole technical reason why and providing articles to back it up, we don't use black.

---
issue created: #464

**Comment by ExperimentsInHonesty** [comment]
The layout of the title should not be stacked and the download button txt should not be stacked when there is plenty of space on the page

If we are on mobile, the elements would get stacked and be smaller but "Download All" never needs to be two lines
![image](https://user-images.githubusercontent.com/37763229/131056661-1ed9b591-5a59-415b-91b6-4ad4f57e7b75.png)

Issue created: #463

**Comment by ExperimentsInHonesty** [comment]
I have issues with the slider at the bottom, but until we have a new designer on the site, I am just putting a pin in it, so that we can discuss our options then.

**Comment by ExperimentsInHonesty** [comment]
The spacing between the post squares don't match from the two sections
The space between the buttons for social media and the posts below is larger than is indicated on the figma
![image](https://user-images.githubusercontent.com/37763229/131057487-efcc4e87-322d-4bb8-9c0d-a7a5daac6873.png)

Issue #465 created for this.

**Comment by susantangux** [comment]
"Press" desktop and mobile webpage images exported from Figma. Please compare live site to these Figma image files:
<img width="1440" alt="Press Kit_Desktop" src="https://user-images.githubusercontent.com/78511203/131231968-c5adf566-4144-4844-b697-86823bb1b883.png">
<img width="360" alt="Press Kit_Mobile" src="https://user-images.githubusercontent.com/78511203/131231972-ec92f6e5-4662-40ed-a32d-f15f0e4fc1c3.png">

**Comment by nahyungkim1220** [comment]
Thank you for the Figma images, Susan!

One thing I noticed is the button count isn't matching on pc (chrome, windows 10). Wondering if this was intentional to exclude LinkedIn from our socials?

**Figma**
![image](https://user-images.githubusercontent.com/43450074/131430320-2cb4820a-04c8-4b30-a405-1b33bbcbc63e.png)

**Live Page**
![image](https://user-images.githubusercontent.com/43450074/131430286-ad04e1f2-a6af-45fb-87d1-e1e8f938bf5d.png)

**Comment by nahyungkim1220** [comment]
Apologies! accidentally clicked the "Close with comment" button. 

Buttons and words overlap when the browser is minimized (chrome, windows 10).

![image](https://user-images.githubusercontent.com/43450074/131431171-a493ccf7-5908-4adb-a1dc-9cf092926174.png)

**Comment by nahyungkim1220** [comment]
Small formatting: Logo and Team buttons could be resized to horizontally align.

![image](https://user-images.githubusercontent.com/43450074/131431565-6c5714d3-26ac-44ed-987e-25833cca5cb7.png)

also noted by bonnie

Issue #466 created for this

**Comment by nahyungkim1220** [comment]
Image sizes on PC don't match Figma. 

**Figma**
![image](https://user-images.githubusercontent.com/43450074/131433811-bba5bb98-d741-4ae1-9d65-93f7d698d176.png)

**Live Page**
<img src = "https://user-images.githubusercontent.com/43450074/131433949-2ef0b5d3-fd22-4df7-8607-a0b2d0e7cfd9.png" width = "385" />

**Comment by nahyungkim1220** [comment]
Image size changes depending on the button in PC. (Wondering if it's intentional to match the post formatting on different socials?)

**Figma**
![image](https://user-images.githubusercontent.com/43450074/131443612-750122f9-7c6b-42f3-a029-992a0165c83a.png)
\
\
**Live Page**
**Facebook**
<img src = "https://user-images.githubusercontent.com/43450074/131434048-7ddf40ec-37d1-492a-8123-0e38ec16c5c9.png" width = "500" />

**Twitter** (slightly narrower and wider than Facebook, change is more visible on live page)
<img src = "https://user-images.githubusercontent.com/43450074/131434079-1934690c-ff5e-45ae-a22a-ce731d089945.png" width = "500" />

**Instagram**
<img src = "https://user-images.githubusercontent.com/43450074/131434108-13baca66-d75b-4239-a943-4c50713a69ca.png" width = "500" />

**Comment by nahyungkim1220** [comment]
Really minor, but download button font color and design don't match on PC and mobile.

**Figma**
<img src = "https://user-images.githubusercontent.com/43450074/131434554-52c8cba6-4934-4539-9642-186b4e6425fd.png" width = "100" />

**Live Page**
<img src = "https://user-images.githubusercontent.com/43450074/131434400-bb97fdee-2d7a-4c78-8707-4a9d94791dfe.png" width = "100" />

on purpose

**Comment by nahyungkim1220** [comment]
<img src= "https://user-images.githubusercontent.com/43450074/131445621-89ce64c2-3557-46cd-a93a-fb7f25f7dea5.png" width = "200" />
The Press Release button (above) leads to our final draft in google docs. It would be better if it lead to its own page or opened as a pdf. It's probably a placeholder link until our hard launch (date published needs edit), but wanted to leave a note for the future. 

For now, created a pdf copy saved in the press release [doc folder](https://drive.google.com/drive/u/1/folders/1ofNg41tnLcCC75darf3aHU0Qj_QztJhS) in case we want to make this change in the soft launch.

**also noted by Bonnie**

Issue #468 created for this

**Comment by henlatourrette** [comment]
> Image size changes depending on the button in PC. (Wondering if it's intentional to match the post formatting on different socials?)
> 
> **Figma** ![image](https://user-images.githubusercontent.com/43450074/131443612-750122f9-7c6b-42f3-a029-992a0165c83a.png) **Live Page** **Facebook** <img alt="" width="500" src="https://user-images.githubusercontent.com/43450074/131434048-7ddf40ec-37d1-492a-8123-0e38ec16c5c9.png">
> 
> **Twitter** (slightly narrower and wider than Facebook, change is more visible on live page) <img alt="" width="500" src="https://user-images.githubusercontent.com/43450074/131434079-1934690c-ff5e-45ae-a22a-ce731d089945.png">
> 
> **Instagram** <img alt="" width="500" src="https://user-images.githubusercontent.com/43450074/131434108-13baca66-d75b-4239-a943-4c50713a69ca.png">

This was intentionally since different social media platforms have different image sizes for their posts.

**Comment by henlatourrette** [comment]
Since most bugs were already considered in issue #433, I propose closing this issue.
