### ISSUE TITLE
Bug Tracking: All Guides Page

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#427]
### Overview

We need to define the problems with the "All Guides page" on the site so that we can fix or delay the fixes until after MVP

### Action Items
- [x] In a comment below: Identify a bug 
  - [x] provide a screen shot of problem
  - [x] details on how to replicate
  - [x] provide any appropriate links that would be useful.
- [ ] Product/development will review the bugs, combine related coding into new issues and determine prioritization for them.

### Resources
- [All Guide Page](https://100automations.org/all_guides) 
- [Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373)

**Bug Priority Code:**
- :heart: - not broken/not fixing 
- :eyes: - need to take a look
- :rocket: - broken/high priority
- :+1: - issue logged/created : #433

**Comment by susantangux** [comment]
"All Guides" desktop and mobile webpage images exported from Figma. Please compare live site to these Figma image files:
<img width="1440" alt="All Guides_Desktop" src="https://user-images.githubusercontent.com/78511203/131231982-87d33d1f-8638-40e3-bd2c-3515d98f93db.png">
<img width="440" alt="All Guides_Mobile" src="https://user-images.githubusercontent.com/78511203/131231984-66f4a152-894b-4c4a-aac8-730309fd7e2e.png">

**Comment by henlatourrette** [comment]
![image](https://user-images.githubusercontent.com/21250505/131757491-7c697636-fd0c-4b38-9cc6-7345d4b32493.png)


The "Guides" title on the top menu is not in Bold as in Figma.
To replicate, you can go to the Guides page and you would not see the "Guides" title in Bold.

**sitewide: nav menu highlighting** 
**added to list in #433, issue will be created**

**Comment by henlatourrette** [comment]
![E5938512-C3FD-45A9-AF61-9752106F8452](https://user-images.githubusercontent.com/21250505/131758082-9e8ad443-c66f-4f65-8150-a388a98292f4.png)

The Hamburger Menu is too small on Mobile. 

To reproduce the error, just go to 100automations.org/all_guides from a mobile browser

**Issue created:** #436

**Comment by susantangux** [comment]
Great catch, Henry! "Guides" in the upper right hand corner is bolded so that users know which page they're on. In fact, this should happen on the "About" and the "Press" pages too, but not "Automations" because that's just a section of the homepage.

**Comment by susantangux** [comment]
Mobile - Yes, Henry is right. The hamburger menu is too small on mobile for all pages. Also, the bottom border of the page should have a border radius of 40px (different from 100px for desktop). The mobile footer is also different from Figma.
![81787](https://user-images.githubusercontent.com/78511203/131784254-7c1d725d-2a8e-4561-adcb-f1cbde72b47d.jpg)

**added to list in #433**

**Comment by susantangux** [comment]
Mobile page's bottom radius and footer in Figma for comparison. See location of text and Hack For LA logo. Social icons should be vertically center justified, and spaced farther apart.
![image](https://user-images.githubusercontent.com/78511203/131784615-b2a77090-833b-4b52-a146-aaeb4958c186.png)

To reproduce the error, simply go to 100automations/all_guides on the mobile browser.
BTW - I updated the mobile design in Figma by taking out the "suggest a guide" button.

**Comment by henlatourrette** [comment]
Since all reported bugs were already considered in issue #433, I propose closing this issue.
