### ISSUE TITLE
Bug Tracking: Guides

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#428]
### Overview

We need to define the problems with the Guides pages on the site so that we can fix or delay the fixes until after MVP

### Action Items
- [x] In a comment below: Identify a bug 
  - [ ] provide a screen shot of problem
  - [ ] details on how to replicate
  - [ ] provide any appropriate links that would be useful.
- [x] Product/development will review the bugs, combine related coding into new issues and determine prioritization for them.

### Resources
- [All Guide Page](https://100automations.org/all_guides) bugs for this page go on this issue #427, but you can navigate to each guide by starting at the All Guide Page
- [Figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A6373)

**Bug Priority Code:**
- :heart: - not broken/not fixing 
- :eyes: - need to take a look
- :rocket: - broken/high priority
- :+1: - issue logged/created : #433

**Comment by susantangux** [comment]
Individual "Guide" desktop and mobile webpage images exported from Figma. Please compare live site to these Figma image files:
<img width="1440" alt="Guide_Desktop" src="https://user-images.githubusercontent.com/78511203/131231995-2c169e85-51b0-4277-9292-61b7d9d4ca99.png">
<img width="441" alt="Gide_Mobile_TOC Collapsed" src="https://user-images.githubusercontent.com/78511203/131231999-0ef8c16d-a0d0-46e0-82e1-4d7f6b0431c5.png">
<img width="360" alt="Guide_Mobile_TOC Expanded" src="https://user-images.githubusercontent.com/78511203/131232005-e9c3818f-d813-499c-8cfa-0413f635129d.png">

**Comment by superbunker** [comment]
from @ExperimentsInHonesty via slack: 

On this file we need to change out the url the image is coming from to come from the repo
https://github.com/100Automations/Website/blob/gh-pages/_guides/project_card_anatomy.md
The image is coming from ![project card anatomy image]https://raw.githubusercontent.com/100Automations/Website/gh-pages/assets/images/guides/project_card_anatomy-0320_1319.png but should be located in the repo instead. (edited)

Issue created #462

**Comment by henlatourrette** [comment]
![397E8E23-92D9-44FF-ADDA-64EC037E1055](https://user-images.githubusercontent.com/21250505/131925013-dbbc8560-86a8-40bf-acc0-570551b797f3.png)
While using the Mobile Safari Browser on my iPhone SE 2020, I see that the bottom of the "guide container" is not centered with the footer. This is happening on all the Guides.

**probably sitewide issue with mobile margins** : #438

**Comment by henlatourrette** [comment]
![C204B50D-9AC6-45A2-A26D-0C6AD4E97059](https://user-images.githubusercontent.com/21250505/131925567-e6b913dd-3eeb-4a5e-abfc-1d9b086c7bfc.png)

For the Mobile version, when there's an image included, it expands the whole Guide container to the right according to the size of the image. 

It is happening on the "Builders' Guide"
https://100automations.org/guides/workflow-guide-for-builders.html


this issue is being worked on for desktop - this mobile issue looks more severe

**potentially related to issue #438**

**Comment by henlatourrette** [comment]
- Since all reported bugs were already considered in issue #433, I propose closing this issue.
