### ISSUE TITLE
Make issues from the bug hunt comments

### ISSUE THREAD

**Issue by superbunker** [100Automations/Website#433]
## Overview
Review the bug hunt comments, correlate associated reports, identify higher priority problems, create issues to address 

## Action Items
 - [x] Collect bug reports from the bug tracking issues
   - @henlatourrette : Home and About
   - @superbunker : All Guides and the Guides
   - @sobe-an : Press section
 - [x] List issues here in a comment
    - summarize bug with title-length description
    - link to original bug tracking comment
- [ ] Add descriptions to New Bugfix Issues list
   - try to identify highest priority/obviously broken stuff
   - Bonus: correlate related reports suggesting underlying problems 
- [ ] Create issues by priority/severity
   - [ ] add relevant info and links
   - [ ] go to original bug tracking issue, add issue number to source comment, and hide comment

## New Bugfix Issues: 
 - [x] #434
 - [x] #436 :rocket:
 - [x] #438 :rocket:
 - [x] #440
- [x] #451
   - https://github.com/100Automations/Website/issues/426#issuecomment-906828203,
   - https://github.com/100Automations/Website/issues/426#issuecomment-908844584
 - [x] #453
    - https://github.com/100Automations/Website/issues/427#issuecomment-910883524
- [ ] Press release layout and Download button font color and design doesn't match Figma 
  :rocket:  #459 
- [ ] #462 
- [ ] #463
- [ ] #464

### not quite issues yet:
- [ ] mobile: bottom border radius is wrong (sitewide) :eyes: #272  
   - https://github.com/100Automations/Website/issues/427#issuecomment-911176851
   - https://github.com/100Automations/Website/issues/427#issuecomment-911180984

## Resources
 - #300
    - #343 
       - #424
       - #425
       - #426
       - #427
       - #428

**Bug Priority Code:**
- :heart: - not broken/not fixing 
- :eyes: - need to take a look
- :rocket: - broken/high priority
- :+1: - issue logged/created

**Comment by superbunker** [comment]
@superbunker doing some tracking/correlating/note-taking here

<details>
<summary>note to self:</summary>
this is how you make folding content
</details>

**Sitewide:**
 - nav menu highlighting
 - mobile menu size

Press page buttons
 - change shape on resize
 - at small size, pushes down into line of content below

**Comment by superbunker** [comment]
Example of what we're gunna do:

- [ ] This thing is broken : link_to_comment

**Comment by sobe-an** [comment]
Press Page Bug Issues

- [x] #451 Contact info is distorted when the page dimension is reduced as the page is not responsive. :rocket: 
   https://github.com/100Automations/Website/issues/426#issuecomment-906828203,
   https://github.com/100Automations/Website/issues/426#issuecomment-908844584
- [x] Margins don't match Figma. :rocket: 
   https://github.com/100Automations/Website/issues/426#issuecomment-906840500
- [x] Link to logo leads to a different folder that is not the folder for logo assets.  (already fixed)
   https://github.com/100Automations/Website/issues/426#issuecomment-906846930
- [x] Page is not responsive as the cards get distorted when the dimension is reduced. 
   https://github.com/100Automations/Website/issues/426#issuecomment-906848000
- [x] #464  :eyes: 
   https://github.com/100Automations/Website/issues/426#issuecomment-906848453
- [x] #463  :eyes:
   https://github.com/100Automations/Website/issues/426#issuecomment-906851058 
- [x] slider at the bottom of the page. :eyes:
   https://github.com/100Automations/Website/issues/426#issuecomment-906851792
- [x] #465  :eyes: 
- [x] Compare live site to Figma image files for desktop and mobile version. 
   #458 
- [x] LinkedIn excluded from our socials on the live page. 
   https://github.com/100Automations/Website/issues/426#issuecomment-908841247
- [x] #466 
- [x] Image sizes on PC don't match Figma.
   https://github.com/100Automations/Website/issues/426#issuecomment-908854716
- [x] Image size changes depending on the social media button in PC
   https://github.com/100Automations/Website/issues/426#issuecomment-908854825
- [x] Download button font color and design don't match on PC and mobile Figma design
   https://github.com/100Automations/Website/issues/426#issuecomment-908869749
- [x] The Press Release button leads to final draft in google docs instead of its own page or a pdf.
   https://github.com/100Automations/Website/issues/426#issuecomment-908901776

**Comment by henlatourrette** [comment]
Home Page Bug Issues

- [x] #438 
- [x] #437

**Comment by henlatourrette** [comment]
About Page Bug Issues

- [x] #439 
- [x]  #442 
- [x]  #444 
- [x]  #445 
- [x]  #446 
- [x]  #447 
- [x]  #448 
- [x]  #449 

Important to notice: Screenshots taken for the Mobile Bugs were from responsive screen, not mobile.

**Comment by superbunker** [comment]
### Guides bugs:

- [ ] change image location : #462 (
https://github.com/100Automations/Website/issues/428#issuecomment-908902329 :eyes: )
- [x] bottom border goes offscreen to the right  : https://github.com/100Automations/Website/issues/428#issuecomment-912108957
   - likely related to sitewide (?) mobile margins issue : #438 🚀 
- [x] mobile images going way offscreen  :rocket: : https://github.com/100Automations/Website/issues/428#issuecomment-912113159 
   - issue #417

**Comment by superbunker** [comment]
### All Guides page bugs

- [x] nav menu highlighting (sitewide) : https://github.com/100Automations/Website/issues/427#issuecomment-910883524
- [x] tiny hamburger (sitewide) :rocket: : https://github.com/100Automations/Website/issues/427#issuecomment-910890624
- [x] #468 mobile: bottom border radius is wrong (sitewide) :eyes: :

**Comment by citrusapple** [comment]
testing

**Comment by henlatourrette** [comment]
I went through all the bugs reported in the comments and it seems to me that there's no pending issue to be created from the reported Bugs.

**Comment by henlatourrette** [comment]
Closing the issue. Bug hunt is done.
