### ISSUE TITLE
Cleanup project board, labels and milestones

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#456]
### Overview
We need to be able to sort the board easily in order to track feature development, velocity, and capacity

### Action Items
- [ ] Make sure all issues have the following label categories
   - [ ] role
   - [ ] size
   - [ ] feature
   - [ ] milestone
   - [ ] optional labels: epic, time sensitive, bug
- [ ] Create shortcuts to check to make sure all issues have the correct labels
- [ ] Periodically check the board to keep it up to date

### Resources
[All issues that don't have size or size missing](https://github.com/100Automations/Website/issues?q=is%3Aopen+is%3Aissue+-label%3A%22size%3A+1pt%22+-label%3A%22size%3A+2pt%22+-label%3A%22size%3A+3+pt%22+-label%3A%22size%3A+5+pts.%22+-label%3A%22size%3A+8+pt.%22+-label%3A%22size%3A+12pt%2B%22+-label%3A%22size%3A+missing%22+-label%3A%22size%3A+epic%22)

[All issues that don't have role or role missing](https://github.com/100Automations/Website/issues?q=is%3Aopen+is%3Aissue+-label%3A%22role%3A+administrative%22+-label%3A%22role%3A+back+end%22+-label%3A%22role%3A+content+writing%22+-label%3A%22role%3A+front+end%22+-label%3A%22role%3A+marketing%22+-label%3A%22role%3A+missing%22+-label%3A%22role%3A+product%22+-label%3A%22role%3A+project+management%22+-label%3A%22role%3A+UI%2FUX%22)

[All issues that don't have feature or feature:missing ](https://github.com/100Automations/Website/issues?q=is%3Aopen+is%3Aissue+-label%3A%22feature%3A+accessibility%22+-label%3A%22feature%3A+GitHub+board%2Fonboarding%22+-label%3A%22feature%3A+image+utilities%22+-label%3A%22feature%3A+missing%22+-label%3A%22feature%3A+outreach%22+-label%3A%22p-feature%3A+About%22+-label%3A%22p-feature%3A+automations%22+-label%3A%22p-feature%3A+Guides+homepage%22+-label%3A%22p-feature%3A+guides%22+-label%3A%22p-feature%3A+Homepage%22+-label%3A%22p-feature%3A+Press%22)

[Issues with size missing](https://github.com/100Automations/Website/issues?q=is%3Aopen+is%3Aissue+label%3A%22size%3A+missing%22)

[Issues with feature missing](https://github.com/100Automations/Website/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+missing%22)

[Issues with role missing](https://github.com/100Automations/Website/issues?q=is%3Aopen+is%3Aissue+label%3A%22role%3A+missing%22)

[Issues that are not on Project Boards](https://github.com/100Automations/Website/issues?q=is%3Aissue+no%3Aproject+is%3Aclosed)

**Comment by henlatourrette** [comment]
I've now updated the "role: missing" labeled issues to their actual roles. 

I have doubts about which feature some more general issues should be labeled with.

**Comment by ExperimentsInHonesty** [comment]
update the link for 
[All issues that don't have feature or feature:missing ](https://github.com/100Automations/Website/issues?q=is%3Aopen+is%3Aissue+-label%3A%22feature%3A+accessibility%22+-label%3A%22feature%3A+GitHub+board%2Fonboarding%22+-label%3A%22feature%3A+image+utilities%22+-label%3A%22feature%3A+missing%22+-label%3A%22feature%3A+outreach%22+-label%3A%22p-feature%3A+About%22+-label%3A%22p-feature%3A+automations%22+-label%3A%22p-feature%3A+Guides+homepage%22+-label%3A%22p-feature%3A+guides%22+-label%3A%22p-feature%3A+Homepage%22+-label%3A%22p-feature%3A+Press%22)

**Comment by ExperimentsInHonesty** [comment]
Audit 2021-12-04
size: 68
feature:
role: 0
