### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/Website#473]
### Overview
We need a roadmap so that we know how to prioritize tasks and how far along we are on the project

### Action Items
- [x] Setup a spreadsheet
- [x]  Define goal of project
- [ ]  Define Objectives
- [ ]  order the objectives in terms of priority
- [ ]  Create milestones
- [ ]  add milestone links to sheet
- [ ]  add current labels to the spreadsheet so that we can identify which of the milestones might be missing labels.
- [ ]  add milestones to all the issues
- [ ]  check in month to see if the milestones are working and what other improvements we might need to make.

### Resources/Instructions
[100 Automations roadmap spreadsheet](https://docs.google.com/spreadsheets/d/1Lv3aMlsHlycPXunTPjSyZgfH4TFRItk_lBn-keipuBU/edit#gid=0)
[Project Milestones](https://github.com/100Automations/Website/milestones)
[HackforLA Website Roadmap](https://docs.google.com/spreadsheets/d/1g3QQH2qsWGa11KgpvE-RdlhEfqD-8gdw1TJAV0LNzl8/edit#gid=1754442892)

**Comment by henlatourrette** [comment]
@ExperimentsInHonesty can you give me access to the HackforLA Website Roadmap (just as a viewer) so that we can use it as an example.

**Comment by henlatourrette** [comment]
I already have access to the HFLA website's roadmap so I'm using it as a sample. We still need to define whether or how we describe the current status for each item in the roadmap.

**Comment by henlatourrette** [comment]
I'm currently comparing our Spreadsheet roadmap with the one for Hack for LA Website. 

I believe we need to have something "more graphical" so that team members could understand better where we are and where are we heading to.

In the meantime, here's a brief of what we have and don't have yet on the Spreadsheet at this point - Sorted out by Main Category or "Strategic Focus Area"

1- Organizational 
- Compliance
- Security
- Org Requirements
- Project Management

2- Infrastructure
- Internal Standards Creation
- External Standards Creation

3- Product Design [ This might be already done but it's not yet on our Spreadsheet ]
- Product Description
- User Personas
- Target Market

4- User Interface Design [ This might be already done but it's not yet on our Spreadsheet ]
- Figma mockups
- Website Design

5- User Experience [ This might be already done but it's not yet on our Spreadsheet ]
- Contributing Process Setup
- Guides
- Usability tests

6- Growth [not done yet and not on the spreadsheet yet]
- User Acquisition Strategy Setup
- Marketing Tools

**Comment by henlatourrette** [comment]
There's already a Roadmap that was written for the Wiki:

https://github.com/100Automations/Website/wiki/Project-Definition-&-Roadmap

We would need to align the information and update the objectives. I'm still working on reviewing that part - but in general, the Roadmap from the Wiki looks obsolete.

**Comment by henlatourrette** [comment]
I named the "categories" as Strategic Focus Areas from which will derive the main "Objectives" or Milestones and Key Results. Still working on updating the Roadmap.

**Comment by henlatourrette** [comment]
As an update, I've added information to [the Roadmap spreadsheet](https://docs.google.com/spreadsheets/d/1Lv3aMlsHlycPXunTPjSyZgfH4TFRItk_lBn-keipuBU/edit#gid=1023813919).

I've grouped the Milestones to their correspondent Strategic Focus Area, but "Objectives" still need to be defined for each of them. 
Nonetheless, I believe that these Milestones might not be directly converted into items on a Roadmap but they should be taken care of as "Health Metrics".
Based on what we've been working on in the past few weeks, I believe that our current Roadmap is or should be as follows - this can be redefined, of course.
- #352 
 We are actively working on this one and it has to do with our User Experience.
- #487 
 This is related to our main Infrastructure and it's key to future growth.
- #484 
 Also related to infrastructure - still a few pending files to be moved.
- We need to update our whole communication from Github and the Site so that they are consistent with each other, there's no issue with this yet I think but we should probably wait for the final User Experience to be defined.

There is other stuff that we also need to be working on but we'd need to define them as a team and also check what can new members work on.
