### ISSUE TITLE
Review and revise the starting point guides

### ISSUE THREAD

**Issue by citrusapple** [100Automations/Website#477]
## Overview
Some of the six _How to Get Started_ guides need urgent revisions so users can move forward. This issue will track the work on the starting point guides, with separate issues for more specific tasks.

## Dependancy

- #469 

## Action Items
- [ ] Review the [starting point guides](https://100automations.org/all_guides) for obvious blockers (eg: create a repository), note here in comments
- [ ] Decide if this guide structure is the best way to handle it for MVP
- [x] #482
- [ ] #481
- [x] #478
- [x] #483

### Possible Action Items (discuss!)
- [ ] [Workflow Guide for Ideators](https://100automations.org/guides/workflow-guide-for-ideators.html): clarify that it's the FutureAutomations kanban overview
- [ ] [Workflow Guide for Builders](https://100automations.org/guides/workflow-guide-for-builders.html): clarify that it's the FutureAutomations kanban overview
- [ ] discuss how the starting point guides should ideally be structured (how long, how detailed, how many)

## Additional Resources
- *Get Started* Guides:
  - source: [Creator Overview](https://github.com/100Automations/Website/blob/gh-pages/_guides/creator_overview.md)
  - source: [Submit Idea](https://github.com/100Automations/Website/blob/gh-pages/_guides/submit_idea.md)
  - source: [Start Building](https://github.com/100Automations/Website/blob/gh-pages/_guides/start_building.md)
  - source: [Start Contributing](https://github.com/100Automations/Website/blob/gh-pages/_guides/start_contributing.md)

**[overall workflow diagram](https://www.figma.com/file/IL9pYQDnj1V0emSZK3UECa/workflow%3A-builder?node-id=0%3A1)**

**Comment by citrusapple** [comment]
reviewed and made comments to [submit ideas guide](https://docs.google.com/document/d/14GvTR5uEtUYg-mphVNV0rSsVWJKZZXWSk4HUniEtnc4/edit#) (i.e. removed verbiage for devs to create new issue directly on project board) as suggested by @superbunker
