### ISSUE TITLE
Milestone Management

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#508]
### Dependency
https://github.com/100Automations/Website/issues/473

### Overview
We need to make an issue to check each milestone so that we can determine if we have made all the issues for that milestone

### Action Items

- [x]  Make an issue for each milestone using this template (skip 1-5 milestones for now)
- [ ]  Once each milestone issue is closed, update this issue with timeline/points/resources required and add the next milestone issue as the dependency

### Resources/Instructions
Use this template for the new issues you will create
```

Milestone/Issue check: [name of milestone]
### Overview
We need to check the [name of milestone ] milestone to see if it has all the issues required to deliver it

### Action Items

- [ ] Grab the details from the milestone and put them into this issue
- [ ] Uncheck the boxes for the labels
- [ ] Add issue links to each label that we have already made the issue, and check as you go if you think that it will only require that one (e.g, it might have the label usability testing, and we are doing three usability testing inside of the milestone, so you would not check it off yet.
- [ ] Add the link to this milestone issue to the Milestone itself

### Resources
[100 Automations Milestone page](https://github.com/100Automations/Website/milestones)
```
[100 Automations Milestone page](https://github.com/100Automations/Website/milestones)

## Check Milestone Issues

- [ ] #517 
- [ ] #518 
- [ ] #519 
- [ ] #520 
- [ ] #521 
- [ ] #522 
- [ ] #523 
- [ ] https://github.com/100Automations/Website/issues/524

### Resources
[100 Automations Milestone page](https://github.com/100Automations/Website/milestones)
#473
