### ISSUE TITLE
Milestone/Issue check: 3 - Website Requirements Gathering

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#519]
### Overview
We need to check the [3 - Website Requirements Gathering](https://github.com/100Automations/Website/milestone/1) milestone to see if it has all the issues required to deliver it

### Action Items

- [ ] Grab the details from the milestone and put them into this issue
- [ ] Uncheck the boxes for the labels
- [ ] Add issue links to each label that we have already made the issue, and check as you go if you think that it will only require that one (e.g, it might have the label usability testing, and we are doing three usability testing inside of the milestone, so you would not check it off yet.
- [ ] Add the link to this milestone issue to the Milestone itself

### Resources
[100 Automations Milestone page](https://github.com/100Automations/Website/milestones)
